### PR TITLE
implement image recency

### PR DESCRIPTION
**Pull request by nicks**
Hello @ellenkorbes,

Please review the following commits I made in branch nicks/recent:

8f6dffad011874151a0fb6e13717ef4cadf1e80b (2020-04-10 12:53:34 -0400)
implement image recency

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
I couldn't figure out how to implement server-based recency without changing the server API to store some metadata about the image (i.e., whether it's an "original" image or an image where filters have been applied already). maybe that's OK.

**Comment by nicks** [comment]
(but I tried to structure the code so that if this is easy to do, it should be as simple as adding the right server calls in getInitialProps())

**Comment by ellenkorbes** [comment]
How much work would it be to implement a button next to Reset called History, that shows thumbnails for the X top results returned from `/list` on the storage service?

Or that simply shows that list somewhere, somehow? This would provide everything I need.

**Comment by nicks** [comment]
Sure! I added a little history button. I put it on the bottom-right of the image selection pane, since it's not really part of the main flow of filter application. Here's what it looks like.

Screenshot from 2020-04-10 14-23-50

Screenshot from 2020-04-10 14-24-05

**Comment by ellenkorbes** [comment]
After applying a filter, the History button doesn't do anything until I press Reset. Is that intended?

**Comment by nicks** [comment]
ah, good find! ya, i went back and forth on only making it accessible from the selection view. i added a reset() to fix that problem.

**Comment by ellenkorbes** [comment]
Great, thanks!

**Pull request merged**
