### PR TITLE
Add styling to the header

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu, @ellenkorbes,

Please review the following commits I made in branch nicks/header:

74b09cc3000f71c7f55c8a62ecc2510decbf130d (2020-04-08 18:13:42 -0400)
Add styling to the header

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
Screenshot from 2020-04-08 18-16-52
Screenshot from 2020-04-08 18-16-34
Screenshot from 2020-04-08 18-16-11

**Comment by nicks** [comment]
I'm going to do a separate design pass on the main pane. Then I think we'll be pretty good!

@ellenkorbes do you have the source "test" images somewhere?

**Comment by ellenkorbes** [comment]
Functionally everything works, two nits though:

1. If you play around enabling and disabling filters long enough, this happens, where it applies the red filter on top of the labeler.

image

2. On a larger screen this becomes apparent, the controls are aligned left but the image is aligned center. It feels strange to me.

image

**Comment by nicks** [comment]
tweaked the layout a bit to be more responsive on larger screens

Screenshot from 2020-04-09 11-56-35
Screenshot from 2020-04-09 11-56-20

**Comment by nicks** [comment]
re: applying the filters in order - AFAICT, the protocol looks like this:
filters: {"filter_red":true,"filter_rectangler":true}
and we're relying on the iteration order to enforce the filter order. i wonder if something is mangling the order. would it make more sense to make the protocol an array?
 filters: {"filter_red", "filter_rectangler"}

**Comment by nicks** [comment]
alternatively, we could have the server enforce an absolute ordering...since as you said, there's only one "correct" order...

**Comment by ellenkorbes** [comment]
> we could have the server enforce an absolute ordering

This sounds like the best solution. I'll look into it.

Approving but @hyu might wanna do a pass on the frontend code for correctness.

**Pull request merged**
