### PR TITLE
Add styling to the main pane

### PR DESCRIPTION
**Pull request by nicks**
Hello @ellenkorbes, @hyu,

Please review the following commits I made in branch nicks/ch5877/upload:

87c9968b682c438daa0abe06cd6b84eb03ed1d7d (2020-04-09 17:25:52 -0400)
Add styling to the main pane

8c4cd13301ed4b58c36aa02e5753298485c5f52c (2020-04-09 11:56:41 -0400)
Add styling to the header

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
Screenshot from 2020-04-09 17-26-54
Screenshot from 2020-04-09 17-26-37
Screenshot from 2020-04-09 17-26-15

**Comment by nicks** [comment]
question: do we still need the drag-and-drop? I can add it, but wasn't sure how useful it'd be for a live demo.

**Comment by ellenkorbes** [comment]
> question: do we still need the drag-and-drop? I can add it, but wasn't sure how useful it'd be for a live demo.

_Need?_ Not really. If you like it, feel free to add. No strong opinions here.

**Comment by ellenkorbes** [comment]
Merging to push stuff on top of it.

**Pull request merged**
